# This a cross-file for the f4discovery probe, providing sane default options for it.

[binaries]
c = 'C:/ARMGCC/bin/arm-none-eabi-gcc.exe'
cpp = 'C:/ARMGCC/bin/arm-none-eabi-g++.exe'
ld = 'C:/ARMGCC/bin/arm-none-eabi-gcc.exe'
ar = 'C:/ARMGCC/bin/arm-none-eabi-ar.exe'
nm = 'C:/ARMGCC/bin/arm-none-eabi-nm.exe'
strip = 'C:/ARMGCC/bin/arm-none-eabi-strip.exe'
objcopy = 'C:/ARMGCC/bin/arm-none-eabi-objcopy.exe'
objdump = 'C:/ARMGCC/bin/arm-none-eabi-objdump.exe'
size = 'C:/ARMGCC/bin/arm-none-eabi-size.exe'



[host_machine]
system = 'bare-metal'
cpu_family = 'arm'
cpu = 'arm'
endian = 'little'

[project options]
probe = 'f4discovery'
targets = 'cortexar,cortexm,riscv32,riscv64,at32f4,ch579,efm,hc32,lpc,nrf,nxp,puya,renesas,rp,sam,stm,ti,xilinx'
rtt_support = true
bmd_bootloader = false

[properties]
c_args = ['-DSTM32_HSE_HZ=25000000']
cpp_args = ['-DSTM32_HSE_HZ=25000000']