name: Build Firmware 25MHz

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Clean Black Magic Repository
        run: |
          git clone --recursive https://github.com .

      - name: Inject 25MHz into Configuration
        run: |
          sed -i "s/rtt_support = true/rtt_support = true\n\n[built-in options]\nc_args = ['-DSTM32_HSE_HZ=25000000']\ncpp_args = ['-DSTM32_HSE_HZ=25000000']/g" cross-file/f4discovery.ini

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install gcc-arm-none-eabi meson ninja-build -y

      - name: Configure Meson
        run: |
          meson setup build --cross-file cross-file/f4discovery.ini

      - name: Compile with Ninja
        run: |
          ninja -C build

      - name: Upload Hex Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bmd-f4discovery-25mhz
          path: build/*.hex
