name: Build Firmware 25MHz

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Clean Directory and Clone
        run: |
          mkdir workspace
          cd workspace
          # Указан полный корректный путь к репозиторию
          git clone --recursive https://github.com .
          
          # Автоматически внедряем частоту 25 МГц в конфигурацию
          sed -i "s/rtt_support = true/rtt_support = true\n\n[built-in options]\nc_args = ['-DSTM32_HSE_HZ=25000000']\ncpp_args = ['-DSTM32_HSE_HZ=25000000']/g" cross-file/f4discovery.ini

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install gcc-arm-none-eabi meson ninja-build -y

      - name: Configure and Compile Firmware
        run: |
          cd workspace
          meson setup build --cross-file cross-file/f4discovery.ini
          ninja -C build

      - name: Upload Hex Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bmd-f4discovery-25mhz
          path: workspace/build/*.hex
