name: Build Firmware 25MHz

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install gcc-arm-none-eabi meson ninja-build -y

      - name: Configure Meson
        run: |
          meson setup build --cross-file cross-file/f4discovery.ini

      - name: Compile with Ninja
        run: |
          ninja -C build

      - name: Upload Hex Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bmd-f4discovery-25mhz
          path: build/*.hex
